swagger: "2.0"
info:
  version: "0.0.1"
  title: Task Manager App
# during dev, should point to your local machine
host: 127.0.0.1:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /tasks:
    # binds a127 app logic to a route
    x-swagger-router-controller: task-manager
    get:
      description: Returns tasks to the caller
      # used as the method name of the controller
      operationId: get
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetTasksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Update tasks for the caller
      # used as the method name of the controller
      operationId: put
      parameters:
        - in: body
          name: task
          description: Task to add
          required: true
          schema:
            type: object
            properties:
              task_id:
                type: string
              task_description:
                type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PutTasksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete task for the caller
      # used as the method name of the controller
      operationId: del
      parameters:
        - in: body
          name: task
          description: Task to delete
          required: true
          schema:
            type: object
            required:
              - task_id
            properties:
              task_id:
                type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PutTasksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /task/start:
    x-swagger-router-controller: task-manager
    put:
      description: Start task for the caller
      # used as the method name of the controller
      operationId: start
      parameters:
        - in: body
          name: task
          description: Task to start
          required: true
          schema:
            type: object
            properties:
              task_id:
                type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PutTasksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /task/close:
    x-swagger-router-controller: task-manager
    put:
      description: Close task for the caller
      # used as the method name of the controller
      operationId: close
      parameters:
        - in: body
          name: task
          description: Task to close
          required: true
          schema:
            type: object
            properties:
              task_id:
                type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PutTasksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /task/stop:
    x-swagger-router-controller: task-manager
    put:
      description: Stop task for the caller
      # used as the method name of the controller
      operationId: stop
      parameters:
        - in: body
          name: task
          description: Task to stop
          required: true
          schema:
            type: object
            properties:
              task_id:
                type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PutTasksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
           
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetTasksResponse:
    type: array
    items:
      type: object
      properties:
        task_id:
          type: string
        task_description:
          type: string
  PutTasksResponse:
    type: array
    items:
      type: object
      properties:
        task_id:
          type: string
        task_description:
          type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
